[project]
name = "ShareBlog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "abudulmuizz", email = "abdulmueezabdulraheem99@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "greenlet>=3.3.0",
    "aiosqlite>=0.22.1",
    "sqlalchemy>=2.0.52",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.14.0",
    "pydantic-settings>=2.15.0",
]
